### PR TITLE
feat(update): add update command

### PR DESCRIPTION
**Pull request by hkuczynski**
## Description

This PR adds an update command which updates the CLI.

Usage:
`very_good update`

Closes: #433. 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
Looks great we just need to update the usage tests to include the update command

**Comment by hkuczynski** [comment]
> Looks great we just need to update the usage tests to include the update command

Should I do it manually or is it generated somehow?

**Comment by felangel** [comment]
> > Looks great we just need to update the usage tests to include the update command
> 
> Should I do it manually or is it generated somehow?

You'll need to update the `command_runner_test.dart` to update the expected usage. Let me know if you need any help

**Comment by hkuczynski** [comment]
@

> > > Looks great we just need to update the usage tests to include the update command
> > 
> > 
> > Should I do it manually or is it generated somehow?
> 
> You'll need to update the `command_runner_test.dart` to update the expected usage. Let me know if you need any help

@felangel  Done

**Review by felangel — APPROVED** [review]
LGTM ✅ 🎉

**Pull request merged**
