### PR TITLE
fix: added a progaurd-rules file

### PR DESCRIPTION
**Pull request by fonkamloic**
## Description
For some reason, the absence of a progaurd-rules file causes a Fatal exception in development when a project depends on firebase services. Normally, this exception should occur only in the release mode. The exception is thrown when a debug app is hot reloaded. It looks as follows. 

```
D/ConnectivityManager(21124): requestNetwork; CallingUid : 10345, CallingPid : 21124
D/AndroidRuntime(21124): Shutting down VM
E/AndroidRuntime(21124): FATAL EXCEPTION: main
E/AndroidRuntime(21124): Process: com.tenflr.gameHause.dev, PID: 21124
E/AndroidRuntime(21124): java.lang.RuntimeException: Internal error in Cloud Firestore (22.0.1).
E/AndroidRuntime(21124): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
E/AndroidRuntime(21124): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
E/AndroidRuntime(21124): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(21124): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21124): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(21124): 	at android.app.ActivityThread.main(ActivityThread.java:7045)
E/AndroidRuntime(21124): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21124): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(21124): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
E/AndroidRuntime(21124): Caused by: java.lang.RuntimeException: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY[5])
E/AndroidRuntime(21124): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:325)
```

To avoid this for newbie using the very_good_cli, I have added a progaurd-rules file with default rules, including firebase. I added firebase because it is the most use backend for newbies and since the rules have no effect when firebase is not used.

## Type of Change

The content of the file looks as follows;
```
#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class androidx.lifecycle.** { *; }
-dontwarn io.flutter.embedding.**
-keep class com.google.firebase.** {*;}

```

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by jorgecoca** [comment]
Hi @fonkamloic 👋 

First of all, thank you so much for your contribution! Unfortunately, I believe it does not make much sense to include these changes in `very_good_cli`: the generated project does not have any Firebase dependencies, so adding those Proguard rules is something that not everyone needs. 

Please let us know what you think.
Thank you!

**Comment by fonkamloic** [comment]
Hello @jorgecoca, 

In my view, any good tool offering advanced functionality should also be beginner-friendly. A huge percentage of newbies will use firebase as a backend service. So I think it is better also to have just this extra line
 `-keep class com.google.firebase.** {*;}` 
and save developers from unexpected crashes (not to mention the errors it generates are not trivial). Otherwise, I don't think code obfuscation and minimization by default is a good idea.

**Comment by felangel** [comment]
Hi @fonkamloic 👋 

Can you please share a reproduction sample? I would prefer filing an issue in the appropriate firebase repository instead. I also think it's worth noting that `flutter create` does not appear to generate the proguard rules either so I don't think it belongs in very_good_cli. Thoughts?

**Comment by fonkamloic** [comment]
Hello @felangel 👋, 

I wasn't able to reproduce the error in a test project to share give the size of the project. I think your assumption is correct. proGaurd is not deprecated in favour of R8. I ran the project verbose and piped all the logs to this [gist](https://gist.github.com/fonkamloic/0cd5922e40bed24f8dc462dcd938ecab)

I also noticed the warning that might back your assumption. 
```
[   +1 ms] WARNING: DSL element 'useProguard' is obsolete.

[        ] It will be removed in version 5.0 of the Android Gradle plugin.

[        ] Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard.
```
These are the versions for the firebase package the project depends on
```
  firebase_auth: ^1.0.1
  firebase: ^9.0.0
  cloud_firestore: ^1.0.3
  firebase_core: ^1.0.1
  firebase_storage: ^8.0.0
```

**Comment by felangel** [comment]
Closing this as it should be addressed by #118 👍

**Pull request closed without merging**
